# fly.toml file for deploying ADA to Fly.io
# See https://fly.io/docs/reference/configuration/ for all options

app = "ada-app" # Change this to your Fly.io app name

primary_region = "iad" # Set to your preferred region

[build]
  image = "node:20-bullseye" # Use a Node image for Bun/Node apps

[env]
  NODE_ENV = "production"
  SERVER_PORT = "8080"
  OLLAMA_API_ENDPOINT = "http://ollama:11434"
  # Add other environment variables as needed

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
